### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by tjbartle** [csce3513/Team11#2]
-As a user, I want to see a main menu with game options.
-As a user, I want to select a start button to see my character in the first room map and begin the game.
-As a user, I want to be able to use the the w,a,s,d keys or the arrow keys to move my character around the room.
-As a user, I want to hit a switch somewhere in the room to unlock additional doors.
-As a user, I want to be able to exit rooms through doors on the edges of the room maps.
-As a user, I want to increase my character's energy/health by walking over health objects.
-As a user, I want to see enemies moving around in each room threatening to come in contact with my character.
-As a user, I want to be able to navigate through my different weapons using the q and e buttons on the keyboard.
-As a user, I want to hit the spacebar to attack an enemy with my weapon.
-As a user, I want to see the enemy explode and disappear when my avatar/character strikes him with a weapon.
-As a user, I want to fight my way through multiple rooms until I reach the last room with the enemy boss.
-As a user, I want to fight the enemy boss in the last room in order to beat the game.
-As a user, I want to be able to use the esc button on the keyboard to go to pause menu which includes options to quit, save, change volume.
-As a developer, I want to use class hierarchies and polymorphism to be able to easily add additional characters, weapons, or enemies without writing entirely new code. 
-As a user, I want to see a map indicating what room I am in relative to the dungeon
-As a user, I want said map to have indicators denoting the boss, keys, chests, or unvisited rooms
-As a user, I want different weapons and tools to solve puzzles or defeat enemies
-As a user, I want to be able to save or have multiple lives 
-As a developer, I would like to see a level creator tool so I can easily and intuitively design levels.
-As a user, I want the game to be in color, so I can differentiate between objects more easily.
-As a user I would like highly developed character art to allow for more immersive gameplay.  
-As a user I want to hear walking noises when my character moves across the screen.
-As a user I want to be able to change the mixing of sound (music, FX, etc.) in game.
-As a user I would like to complete puzzles to access new rooms.

**Comment by blainehoyt** [comment]
Ist gut?  These are surprisingly difficult.

**Comment by tjbartle** [comment]
Hey guys, I think what we have is sufficient. In the wikipedia link that Dr. Deaton gave us it mentioned that a user story should fit on a notecard so it doesn't  get too long. I think this is a pretty solid user story.

**Comment by dreamparacite** [comment]
I added a few that were missing, this should all be sufficient

edit: didn't mean to close, issue reopened
